name: Build the site
on:
  push:
     branches:
       - main
jobs:
  Jekyll:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout the Code
           uses: actions/checkout@v2
         - name: Install build requirements
           uses: ruby/setup-ruby@v1
           with:
             ruby-version: 3.3
             bundler-cache: true
         - name: Build the site
           run: |
            BUILD_DIR="${GITHUB_WORKSPACE}/../jekyll_build"
            mkdir $BUILD_DIR
            cd $GITHUB_WORKSPACE
            JEKYLL_ENV=production bundle exec jekyll build -d $BUILD_DIR
         - name: Fetch PDF Template
           uses: dsaltares/fetch-gh-release-asset@master
           with:
             repo: 'Wandmalfarbe/pandoc-latex-template'
             file: 'Eisvogel.tar.gz'
             target: 'eisvogel/Eisvogel.tar.gz'
             token: ${{ secrets.GITHUB_TOKEN }}
         - name: Prepare Pandoc Inputs
           run: |
            cp ../jekyll_build/pdfsource.md ./pdfsource-compiled.md
            cd eisvogel
            gunzip Eisvogel.tar.gz
            tar -xf Eisvogel.tar
            cd Eisvogel-*
            mv eisvogel.latex ../../
         - name: Make the PDF
           uses: docker://rstropek/pandoc-latex:latest
           with:
            args: --output "YogaSutra.pdf" pdfsource-compiled.md --template eisvogel --listings
         - name: Push to GitHub Pages
           run: | 
            mv "YogaSutra.pdf" ../jekyll_build/
            HASH="$(git log -n 1 --format=%H)"
            cd ../jekyll_build
            touch .nojekyll
            git init -b temp
            git config user.name "OBU Build Bot"
            git config user.email "buddhist-uni@users.noreply.github.com"
            git add .
            git commit -m "Automated GitHub build from ${HASH}" --quiet
            git push --force "https://buddhist-uni:${{ secrets.GITHUB_TOKEN }}@github.com/buddhist-uni/patanjali-yoga-sutra.git" temp:production
